static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Communication/OPCaccess/src/ClassFactory.cpp,v 1.1 2008-08-06 16:04:28 andy_gotz Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: andy_gotz $
//
// $Revision: 1.1 $
//
// $Log: not supported by cvs2svn $
// Revision 1.2  2005/09/06 16:26:07  meyer
// Ported to Tango%. Modified attribute structure!
//
// Revision 1.1.1.2  2005/07/12 06:59:36  peru
// Imported using TkCVS
//
// Revision 1.1.1.1  2004/11/08 09:21:08  meyer
// Imported using TkCVS
//
// Revision 1.2  2004/10/27 14:29:09  meyer
// *** empty log message ***
//
// Revision 1.1  2004/10/20 11:42:13  meyer
// Initial revision
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include "StdAfx.h"
#include <tango.h>
#include <OPCaccessClass.h>

/**
 *	Create OPCaccessClass singleton and store it in DServer object.
 *
 * @author	$Author: andy_gotz $
 * @version	$Revision: 1.1 $ $
 */

void Tango::DServer::class_factory()
{

	add_class(OPCaccess_ns::OPCaccessClass::init("OPCaccess"));

}
