#=============================================================================
#
# file :        Makefile.h
#
# description : Include for the OPCaccess class.
#
# project :     Makefile to generate a Tango server
#
# $Author: andy_gotz $
#
# $Revision: 1.1 $
#
# $Log: not supported by cvs2svn $
# Revision 1.2  2005/09/06 16:26:07  meyer
# Ported to Tango%. Modified attribute structure!
#
# Revision 1.1.1.2  2005/07/12 06:59:37  peru
# Imported using TkCVS
#
# Revision 1.1.1.1  2004/11/08 09:21:08  meyer
# Imported using TkCVS
#
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#  		This file is generated by POGO
#	(Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#

ifdef _solaris
CC = CC
#BIN_DIR = solaris9_CC
BIN_DIR=$(shell /csadmin/common/scripts/get_os)_CC
endif

ifdef linux
CC = c++
AR = ar
#BIN_DIR = suse82
BIN_DIR=$(shell /csadmin/common/scripts/get_os)
endif

TANGO_HOME   =  /segfs/tango
INCLUDE_DIRS =  -I$(TANGO_HOME)/include/$(BIN_DIR)	-I.
LIB_DIRS     =  -L $(TANGO_HOME)/lib/$(BIN_DIR)

ifdef _solaris
CXXFLAGS =  -mt -D_PTHREADS $(INCLUDE_DIRS)
LFLAGS =  -g $(LIB_DIRS)  		\
				-ltango			\
				-llog4tango		\
				-lomniORB4 		\
				-lomniDynamic4	\
				-lomnithread	\
				-lpthread		\
				-lCOS4			\
				-lposix4 -lsocket -lnsl
endif

ifdef linux
CXXFLAGS =  -g -D_REENTRANT $(INCLUDE_DIRS)
LFLAGS =  -g $(LIB_DIRS)  		\
				-ltango			\
				-llog4tango		\
				-lomniORB4 		\
				-lomniDynamic4	\
				-lomnithread	\
				-lCOS4			\
				-ldl -lpthread
endif




CLASS =	OPCaccess

SVC_OBJS = 	main.o	\
		ClassFactory.o	\
		$(CLASS)Class.o	\
		$(CLASS)StateMachine.o \
		$(CLASS).o

SVC_INC = 	$(CLASS)Class.h \
			$(CLASS).h


%.o: %.cpp $(SVC_INC)
	$(CC) $(CXXFLAGS) -c $<
			
all: $(CLASS)

$(CLASS):	$(SVC_OBJS)
	$(CC) $(SVC_OBJS) -o $(CLASS) $(LFLAGS)

clean:
	rm -f *.o $(CLASS) core
	
install:
	cp $(CLASS) $(TANGO_HOME)/bin/$(BIN_DIR)
